### ISSUE TITLE
go.uber.org/dosa

### ISSUE THREAD

**Issue by breerly** [uber-go/dosa#224]
I'm happy to setup go.uber.org/dosa; it:

* Only contains uber branding in the import path, so no github
* Removes the - from the import path
* Is really short
* Lets you move the source later if you'd like

Once I do, you can use that import path everywhere.

**Comment by eculver** [comment]
How would we do this without requiring users to have to change their import paths? Didn't yarpc or fx make this transition at some point?

**Comment by breerly** [comment]
It's a breaking change, and users would have to update their import paths.

Thought I'd suggest it before you remove the beta status from your README.

**Comment by eculver** [comment]
@breerly good call. It is a mistake to have not updated the README. Let's discuss how one might go about changing a package name such as this. I have some questions:

* Is a breaking change worthwhile? 
* Do we cut our losses and accept the import path (which `goimports` should take care of) or 
* Are aesthetics really that important in this context and
* Can we make this an example for the future?

**Comment by breerly** [comment]
I think hold off on it for v3
