### ISSUE TITLE
Replace package satori/go.uuid

### ISSUE THREAD

**Issue by josselin-c** [uber-go/dosa#343]
This issue has been opened automaticaly because we think you are using satori/uuid in your code. Unfortunately, satori/uuid has a critical defect where it doesn't generate random UUIDV4s satori/go.uuid#73 and should be replaced as the maintainer has been unresponsive for 5 months with the bug still open. Alternative packages you should consider: https://github.com/google/uuid https://github.com/pborman/uuid

**Comment by rkuris** [comment]
See also https://github.com/gofrs/uuid

**Comment by rkuris** [comment]
See https://github.com/uber-go/dosa/pull/361

**Comment by MaerF0x0** [comment]
Reviving the dead here, but do not see  https://github.com/gofrs/uuid as it's "A UUID package originally forked from github.com/satori/go.uuid"
